#!/bin/bash
./Profile_n_compile.sh 000
./Profile_n_compile.sh 001
./Profile_n_compile.sh 002
./Profile_n_compile.sh 003
./Profile_n_compile.sh 004
./Profile_n_compile.sh 005
#./Profile_n_compile.sh 006
./Profile_n_compile.sh 007
./Profile_n_compile.sh 008
./Profile_n_compile.sh 009
#./Profile_n_compile.sh 010
./Profile_n_compile.sh 0_sum
./Profile_n_compile.sh 1_sum
./Profile_n_compile.sh 2_sum
./Profile_n_compile.sh 0_lenna
./Profile_n_compile.sh 1_lenna
./Profile_n_compile.sh 11_lenna
./Profile_n_compile.sh 2_lenna
./Profile_n_compile.sh 22_lenna
./Profile_n_compile.sh 3_lenna
./Profile_n_compile.sh 33_lenna