extern void init(void);
extern void rbuildlut(void);
extern void gbuildlut(void);
extern void bbuildlut(void);
extern void rbalance(void);
extern void gbalance(void);
extern void bbalance(void);
extern void RnG(void);
extern void finish(void);
